# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nakama' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nakama
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'

  target 'NakamaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NakamaUITests' do
    # Pods for testing
  end

end
